version: 2

jobs:
  macos:
    macos:
      xcode: "9.0"
    steps:
      - run: brew install mongodb
      - run: brew services start mongodb
      - run: sleep 3
      - checkout
      - run: swift build
      - run: swift test

  linux:
    docker:
      - image: swift:4.0.3
      - image: mongo:3.6.1
    steps:
      - checkout
      - run: swift build
      - run: swift test

  # 3.1 backward compat checks

  linux-3:
    docker:
      - image: swift:3.1.1
      - image: mongo:3.6.1
    steps:
      - checkout
      - run: swift build
      - run: swift test

workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-3
      - macos
